/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author wesle
 */
public class ViewDBList extends javax.swing.JFrame {

    /**
     * Creates new form ViewDBList
     */
    public ViewDBList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewDBListBoxList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        viewDBListBtnAdd = new javax.swing.JButton();
        viewDBListBtnEdit = new javax.swing.JButton();
        viewDBListBtnFavorite = new javax.swing.JButton();
        viewDBListBtnDelete = new javax.swing.JButton();
        viewDBListBtnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        viewDBListBoxList.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        viewDBListBoxList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(viewDBListBoxList);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Lista de Conexões Configuradas");

        viewDBListBtnAdd.setBackground(new java.awt.Color(51, 51, 51));
        viewDBListBtnAdd.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        viewDBListBtnAdd.setForeground(new java.awt.Color(255, 255, 255));
        viewDBListBtnAdd.setText("Adicionar");
        viewDBListBtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDBListBtnAddActionPerformed(evt);
            }
        });

        viewDBListBtnEdit.setBackground(new java.awt.Color(0, 51, 204));
        viewDBListBtnEdit.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        viewDBListBtnEdit.setForeground(new java.awt.Color(255, 255, 255));
        viewDBListBtnEdit.setText("Editar");

        viewDBListBtnFavorite.setBackground(new java.awt.Color(0, 153, 51));
        viewDBListBtnFavorite.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        viewDBListBtnFavorite.setForeground(new java.awt.Color(255, 255, 255));
        viewDBListBtnFavorite.setText("Favorito");

        viewDBListBtnDelete.setBackground(new java.awt.Color(204, 0, 153));
        viewDBListBtnDelete.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        viewDBListBtnDelete.setForeground(new java.awt.Color(255, 255, 255));
        viewDBListBtnDelete.setText("Excluir");

        viewDBListBtnCancel.setBackground(new java.awt.Color(255, 0, 0));
        viewDBListBtnCancel.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        viewDBListBtnCancel.setForeground(new java.awt.Color(255, 255, 255));
        viewDBListBtnCancel.setText("Cancelar");
        viewDBListBtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDBListBtnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewDBListBtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(viewDBListBtnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(65, 65, 65)
                            .addComponent(viewDBListBtnFavorite, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewDBListBtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(63, 63, 63)
                            .addComponent(viewDBListBtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewDBListBtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewDBListBtnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewDBListBtnFavorite, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewDBListBtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewDBListBtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(711, 501));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void viewDBListBtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDBListBtnCancelActionPerformed
        this.dispose();
        ViewLogin viewLogin = new ViewLogin();
        viewLogin.setVisible(true);
    }//GEN-LAST:event_viewDBListBtnCancelActionPerformed

    private void viewDBListBtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDBListBtnAddActionPerformed
        ViewConfigDB viewConfigDB = new ViewConfigDB();
        viewConfigDB.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_viewDBListBtnAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewDBList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewDBList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewDBList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewDBList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewDBList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> viewDBListBoxList;
    private javax.swing.JButton viewDBListBtnAdd;
    private javax.swing.JButton viewDBListBtnCancel;
    private javax.swing.JButton viewDBListBtnDelete;
    private javax.swing.JButton viewDBListBtnEdit;
    private javax.swing.JButton viewDBListBtnFavorite;
    // End of variables declaration//GEN-END:variables
}
